/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProductionService } from "../production.service";
import { ProductionCreateInput } from "./ProductionCreateInput";
import { Production } from "./Production";
import { ProductionFindManyArgs } from "./ProductionFindManyArgs";
import { ProductionWhereUniqueInput } from "./ProductionWhereUniqueInput";
import { ProductionUpdateInput } from "./ProductionUpdateInput";
import { MaterialFindManyArgs } from "../../material/base/MaterialFindManyArgs";
import { Material } from "../../material/base/Material";
import { MaterialWhereUniqueInput } from "../../material/base/MaterialWhereUniqueInput";
import { ProductFindManyArgs } from "../../product/base/ProductFindManyArgs";
import { Product } from "../../product/base/Product";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";

export class ProductionControllerBase {
  constructor(protected readonly service: ProductionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Production })
  @swagger.ApiBody({
    type: ProductionCreateInput,
  })
  async createProduction(
    @common.Body() data: ProductionCreateInput
  ): Promise<Production> {
    return await this.service.createProduction({
      data: data,
      select: {
        createdAt: true,
        id: true,
        quantity: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Production] })
  @ApiNestedQuery(ProductionFindManyArgs)
  async productions(@common.Req() request: Request): Promise<Production[]> {
    const args = plainToClass(ProductionFindManyArgs, request.query);
    return this.service.productions({
      ...args,
      select: {
        createdAt: true,
        id: true,
        quantity: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Production })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async production(
    @common.Param() params: ProductionWhereUniqueInput
  ): Promise<Production | null> {
    const result = await this.service.production({
      where: params,
      select: {
        createdAt: true,
        id: true,
        quantity: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Production })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiBody({
    type: ProductionUpdateInput,
  })
  async updateProduction(
    @common.Param() params: ProductionWhereUniqueInput,
    @common.Body() data: ProductionUpdateInput
  ): Promise<Production | null> {
    try {
      return await this.service.updateProduction({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          quantity: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Production })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProduction(
    @common.Param() params: ProductionWhereUniqueInput
  ): Promise<Production | null> {
    try {
      return await this.service.deleteProduction({
        where: params,
        select: {
          createdAt: true,
          id: true,
          quantity: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/material")
  @ApiNestedQuery(MaterialFindManyArgs)
  async findMaterial(
    @common.Req() request: Request,
    @common.Param() params: ProductionWhereUniqueInput
  ): Promise<Material[]> {
    const query = plainToClass(MaterialFindManyArgs, request.query);
    const results = await this.service.findMaterial(params.id, {
      ...query,
      select: {
        category: true,
        createdAt: true,
        id: true,
        lotPrice: true,
        name: true,
        status: true,
        stock: true,
        supplier: true,
        unitPrice: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/material")
  async connectMaterial(
    @common.Param() params: ProductionWhereUniqueInput,
    @common.Body() body: MaterialWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      material: {
        connect: body,
      },
    };
    await this.service.updateProduction({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/material")
  async updateMaterial(
    @common.Param() params: ProductionWhereUniqueInput,
    @common.Body() body: MaterialWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      material: {
        set: body,
      },
    };
    await this.service.updateProduction({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/material")
  async disconnectMaterial(
    @common.Param() params: ProductionWhereUniqueInput,
    @common.Body() body: MaterialWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      material: {
        disconnect: body,
      },
    };
    await this.service.updateProduction({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/product")
  @ApiNestedQuery(ProductFindManyArgs)
  async findProduct(
    @common.Req() request: Request,
    @common.Param() params: ProductionWhereUniqueInput
  ): Promise<Product[]> {
    const query = plainToClass(ProductFindManyArgs, request.query);
    const results = await this.service.findProduct(params.id, {
      ...query,
      select: {
        costPrice: true,
        createdAt: true,
        description: true,
        id: true,
        productName: true,
        profit: true,
        salesPrice: true,
        status: true,
        stock: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/product")
  async connectProduct(
    @common.Param() params: ProductionWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      product: {
        connect: body,
      },
    };
    await this.service.updateProduction({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/product")
  async updateProduct(
    @common.Param() params: ProductionWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      product: {
        set: body,
      },
    };
    await this.service.updateProduction({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/product")
  async disconnectProduct(
    @common.Param() params: ProductionWhereUniqueInput,
    @common.Body() body: ProductWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      product: {
        disconnect: body,
      },
    };
    await this.service.updateProduction({
      where: params,
      data,
      select: { id: true },
    });
  }
}
