/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsString,
  MaxLength,
  IsOptional,
  IsNumber,
  Max,
  ValidateNested,
  IsEnum,
  IsInt,
} from "class-validator";

import { ProductionUpdateManyWithoutMaterialsInput } from "./ProductionUpdateManyWithoutMaterialsInput";
import { Type } from "class-transformer";
import { EnumMaterialStatus } from "./EnumMaterialStatus";

@InputType()
class MaterialUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  category?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  lotPrice?: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: () => ProductionUpdateManyWithoutMaterialsInput,
  })
  @ValidateNested()
  @Type(() => ProductionUpdateManyWithoutMaterialsInput)
  @IsOptional()
  @Field(() => ProductionUpdateManyWithoutMaterialsInput, {
    nullable: true,
  })
  productions?: ProductionUpdateManyWithoutMaterialsInput;

  @ApiProperty({
    required: false,
    enum: EnumMaterialStatus,
  })
  @IsEnum(EnumMaterialStatus)
  @IsOptional()
  @Field(() => EnumMaterialStatus, {
    nullable: true,
  })
  status?: "Available" | "OutOfStock";

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  stock?: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  supplier?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  unitPrice?: number;
}

export { MaterialUpdateInput as MaterialUpdateInput };
