/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { MaterialService } from "../material.service";
import { MaterialCreateInput } from "./MaterialCreateInput";
import { Material } from "./Material";
import { MaterialFindManyArgs } from "./MaterialFindManyArgs";
import { MaterialWhereUniqueInput } from "./MaterialWhereUniqueInput";
import { MaterialUpdateInput } from "./MaterialUpdateInput";
import { ProductionFindManyArgs } from "../../production/base/ProductionFindManyArgs";
import { Production } from "../../production/base/Production";
import { ProductionWhereUniqueInput } from "../../production/base/ProductionWhereUniqueInput";

export class MaterialControllerBase {
  constructor(protected readonly service: MaterialService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Material })
  @swagger.ApiBody({
    type: MaterialCreateInput,
  })
  async createMaterial(
    @common.Body() data: MaterialCreateInput
  ): Promise<Material> {
    return await this.service.createMaterial({
      data: data,
      select: {
        category: true,
        createdAt: true,
        id: true,
        lotPrice: true,
        name: true,
        status: true,
        stock: true,
        supplier: true,
        unitPrice: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Material] })
  @ApiNestedQuery(MaterialFindManyArgs)
  async materials(@common.Req() request: Request): Promise<Material[]> {
    const args = plainToClass(MaterialFindManyArgs, request.query);
    return this.service.materials({
      ...args,
      select: {
        category: true,
        createdAt: true,
        id: true,
        lotPrice: true,
        name: true,
        status: true,
        stock: true,
        supplier: true,
        unitPrice: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Material })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async material(
    @common.Param() params: MaterialWhereUniqueInput
  ): Promise<Material | null> {
    const result = await this.service.material({
      where: params,
      select: {
        category: true,
        createdAt: true,
        id: true,
        lotPrice: true,
        name: true,
        status: true,
        stock: true,
        supplier: true,
        unitPrice: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Material })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiBody({
    type: MaterialUpdateInput,
  })
  async updateMaterial(
    @common.Param() params: MaterialWhereUniqueInput,
    @common.Body() data: MaterialUpdateInput
  ): Promise<Material | null> {
    try {
      return await this.service.updateMaterial({
        where: params,
        data: data,
        select: {
          category: true,
          createdAt: true,
          id: true,
          lotPrice: true,
          name: true,
          status: true,
          stock: true,
          supplier: true,
          unitPrice: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Material })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteMaterial(
    @common.Param() params: MaterialWhereUniqueInput
  ): Promise<Material | null> {
    try {
      return await this.service.deleteMaterial({
        where: params,
        select: {
          category: true,
          createdAt: true,
          id: true,
          lotPrice: true,
          name: true,
          status: true,
          stock: true,
          supplier: true,
          unitPrice: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/productions")
  @ApiNestedQuery(ProductionFindManyArgs)
  async findProductions(
    @common.Req() request: Request,
    @common.Param() params: MaterialWhereUniqueInput
  ): Promise<Production[]> {
    const query = plainToClass(ProductionFindManyArgs, request.query);
    const results = await this.service.findProductions(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        quantity: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/productions")
  async connectProductions(
    @common.Param() params: MaterialWhereUniqueInput,
    @common.Body() body: ProductionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productions: {
        connect: body,
      },
    };
    await this.service.updateMaterial({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/productions")
  async updateProductions(
    @common.Param() params: MaterialWhereUniqueInput,
    @common.Body() body: ProductionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productions: {
        set: body,
      },
    };
    await this.service.updateMaterial({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/productions")
  async disconnectProductions(
    @common.Param() params: MaterialWhereUniqueInput,
    @common.Body() body: ProductionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      productions: {
        disconnect: body,
      },
    };
    await this.service.updateMaterial({
      where: params,
      data,
      select: { id: true },
    });
  }
}
